### PR TITLE
feat: 🎸 expose event creators

### PR DESCRIPTION
**Pull request by twittwer**
Expose event creator to use them for testing of event processing
services.

Closes: #353

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #353 

## What is the new behavior?

The creator functions for event objects are now available in the public API.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by twittwer** [comment]
@NetanelBasal Are there any tests required in this case as it's just exposing already existing functions?

**Comment by NetanelBasal** [comment]
No, just add yourself to the contributors' list.

**Comment by twittwer** [comment]
Ok, done
Just asking: Is spectator participating in Hacktoberfest?

**Comment by NetanelBasal** [comment]
No

**Pull request merged**
