### PR TITLE
build: upgrade to Angular 11

### PR DESCRIPTION
**Pull request by matheo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #384

## What is the new behavior?

I've updated the failing path from `@schematics/angular/utility/config` to `@schematics/angular/utility/workspace`

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```
Perhaps `Spectator v7.0.0` should be released for Angular 11

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Check the CI, please.

**Comment by matheo** [comment]
According to [this Angular issue](https://github.com/angular/angular/issues/40507), the tests fails on Chrome 83
is there a way to update the Travis settings to upgrade that one? it worked for me locally with Chrome 88:
image

**Comment by NetanelBasal** [comment]
Try https://docs.travis-ci.com/user/chrome

**Comment by matheo** [comment]
YAY! it worked
I'm rebasing to include a breaking-change commit for the v7.0.0 release

**Comment by matheo** [comment]
this is ready to be released @NetanelBasal :tada:

**Comment by NetanelBasal** [comment]
Why should we consider it as a breaking change?

**Comment by matheo** [comment]
Because of https://github.com/ngneat/spectator/issues/384

The `@schematics/angular` paths changed

**Comment by NetanelBasal** [comment]
We forgot to update the peer dependencies to the correct version. See https://github.com/ngneat/spectator/issues/393

**Comment by matheo** [comment]
Oh my... what a detail. Creating the PR now

**Pull request merged**
