### PR TITLE
feat(pipe): add support for testing pipes

### PR DESCRIPTION
**Pull request by kanafghan**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 203

## What is the new behavior?

Adds support for testing pipes which is currently missing.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

This is a WIP on adding support for testing pipes. I need to do the following:

[ ] Write documentation
[ ] Add more test cases
[ ] Create schematic
[ ] Add snippet

I would like to know whether I'm on the right path.

### CODE REVIEW

**Comment by kanafghan** [comment]
I can't see any system in the way tests are organized. Where should I add tests for the `SpectatorPipe` use cases?

**Comment by NetanelBasal** [comment]
@kanafghan create a pipe folder, and add the tests, please.

**Comment by kanafghan** [comment]
@NetanelBasal I have now completed the following:

- [x] Write documentation
- [x] Add more test cases
- [x] Create Schematics
- [x] Add snippets
- [x] Add Jest support

Please do the review and let me know if anything should be changed.

**Comment by NetanelBasal** [comment]
Fantastic work, @kanafghan. I will merge it asap. Thanks.

**Pull request merged**
