### PR TITLE
fix: support Angular 9 #262

### PR DESCRIPTION
**Pull request by zoltan-nz**
Extend angular version number in peerDependencies to support Angular 8/9

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #262 

## What is the new behavior?

No alert any more.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Thanks. Can you confirm that it works fine with the stable latest version (v9)?

**Comment by zoltan-nz** [comment]
@NetanelBasal I just created a separated branch and run an `ng update`. https://github.com/ngneat/spectator/pull/264

Update run without any issue.

`npm run build` raised one issue in `event-objects.ts` where I had to change `initUIEvent` to `initEvent`. https://github.com/ngneat/spectator/pull/264/files#diff-74b3cf777d1a698806fdcf02f363a0ceR28

One test is failing in `spyObject`.
https://travis-ci.org/ngneat/spectator/builds/648787511#L366
https://github.com/ngneat/spectator/blob/master/projects/spectator/test/spy-object/spy-object.spec.ts#L15

**Comment by Wykks** [comment]
This is more correct : `^8.0.0-0 || ^9.0.0-0`.

**Comment by NetanelBasal** [comment]
@zoltan-nz did you have time to find what's causing the issue?

**Comment by zoltan-nz** [comment]
This PR is more promising: https://github.com/ngneat/spectator/pull/267

**Comment by zoltan-nz** [comment]
Closing it. Other PR covers more.

**Pull request closed without merging**
