### PR TITLE
feat: 🎸 upgrade to Angular 15

### PR DESCRIPTION
**Pull request by chimurai**
- updated `jest-preset-angular`
- ran ng update on `@angular/core`, `@angular/cli`, `@angular/cdk` and `@angular-eslint`

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
Upgrade to Angular 15

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

\-

## Does this PR introduce a breaking change?
```
[X] Yes
[] No
```

## Other information
\-

### CODE REVIEW

**Comment by NetanelBasal** [comment]
This is a breaking change

**Comment by chimurai** [comment]
Updated the PR template to `breaking change`

**Comment by NetanelBasal** [comment]
The commit should be updated to include a breaking change based on the standard commits message.

https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit-message-format

**Comment by chimurai** [comment]
Updated the commit message.

Let me know if there are any other remarks.

**Comment by NetanelBasal** [comment]
CI is faliing

**Comment by chimurai** [comment]
Probably due to some config removal by the upgrade scripts. Will take a look 👀

**Comment by chimurai** [comment]
Reverted changes to `projects/spectator/test/test.ts`. Think this is used in karma.

https://github.com/ngneat/spectator/compare/f0e2179428a0d60697004e012af754112a7eb9d4..1722613528fa3bab7358105a5c820519112e3f69

**Comment by mbruning24** [comment]
@chimurai would love to see this PR put in, holding off on our angular 15 upgrade until this is finished.

**Comment by chimurai** [comment]
Thanks for the interest.

Maybe good to share what I've found so far:

When running `"test:ci": "cross-env NODE_ENV=build yarn test && yarn test:jest --silent",`
- `NODE_ENV=build yarn test` is failing ❌
-  `yarn test:jest` is successful ✅

---

Zooming into `NODE_ENV=build yarn test`

```shell
# https://github.com/ngneat/spectator/actions/runs/3676359784/jobs/6230876803

$ cross-env NODE_ENV=build yarn test && yarn test:jest --silent
$ ng test
- Generating browser application bundles (phase: setup)...
✔ Browser application bundle generation complete.

Error: Specified patterns: "**/*.spec.ts" did not match any spec files.


13 12 2022 0[6](https://github.com/ngneat/spectator/actions/runs/3676359784/jobs/6230876803#step:4:7):23:23.044:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:98[7](https://github.com/ngneat/spectator/actions/runs/3676359784/jobs/6230876803#step:4:8)6/
```

Guess this is related to a breaking change in `angular-cli`
https://github.com/angular/angular-cli/blob/main/CHANGELOG.md#1500-2022-11-16

> `require.context` are no longer parsed. Webpack specific features are not supported nor guaranteed to work in the future.

---

Haven't got time to dig into the issue further.
Don't mind to get help on this one.

**Comment by mbruning24** [comment]
I figured out the issue. The new karma builder on angular devkit uses an include glob based off the project src root (which is projects/spectator/src). So, the new "include" option for the builder in angular.json should have `"include": ["../test/test.ts", "../test/**/*.spec.ts"]` so that the paths are picked up relative to the src folder. I have a commit lined up ready for this but I don't have push privileges on your repo @chimurai. You can accomplish this yourself if you want, lmk what you wanna do.

**Comment by chimurai** [comment]
That's awesome news.

Think you should be able to commit now. Could you give it another try?

**Comment by mbruning24** [comment]
```
$ git push
remote: Permission to chimurai/spectator.git denied to mbruning24.
fatal: unable to access 'https://github.com/chimurai/spectator.git/': The requested URL returned error: 403
```

**Comment by mbruning24** [comment]
@NetanelBasal I think I need workflow approval since I'm a first time contributor, just pinging for visibility

**Comment by chimurai** [comment]
Thanks for helping out @mbruning24 !  💪

**Pull request merged**
