### PR TITLE
Feature/fix: toHaveClass should accept classes in any order if configured

### PR DESCRIPTION
**Pull request by YoeriNijs**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
This is a proposal to add additional support for the following by passing an optional config object: https://github.com/ngneat/spectator/issues/361

## Does this PR introduce a breaking change?
```
[] Yes
[x ] No
```

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Thanks for the PR. I prefer to add a configurable option to `toHaveClass`:

```ts
toHaveClass('', { strict: false })
```

**Comment by YoeriNijs** [comment]
Yes, done! I was doubting a bit whether we should pass a config or just a strict boolean, but I guess I prefer the config since we could extend it with more ease eventually (if needed).

Now, our toHaveClass check is not strict anymore. I guess this is not a problem since it was unintended anyway. Agree?

**Comment by NetanelBasal** [comment]
Unfortunately, we can't count on it and break the code for some users. We should make the default `strict: true` for now, and change it to `false` in the next major version.

**Comment by YoeriNijs** [comment]
Done! :)

**Pull request merged**
