### PR TITLE
feat: upgrade to Angular 15.1

### PR DESCRIPTION
**Pull request by czietsman**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

The private api ɵisStandalone is not found when building with Angular 15.1

Issue Number: #598

## What is the new behavior?

The public api isStandalone from Angular 15.1 is used
Spectator should work with Angular >=15.1.0

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

Spectator now requires Angular >=15.1.0

### CODE REVIEW

**Review by k3nsei — APPROVED** [review]

**Comment by WolfSoko** [comment]
Please fastly merge this PR if possible. I also face this problem.

**Comment by czietsman** [comment]
@NetanelBasal I need workflow approval since I'm a first time contributor, just pinging for visibility

**Review by WolfSoko — APPROVED** [review]

**Comment by NetanelBasal** [comment]
This is a breaking change and should be in the commit message.

**Comment by czietsman** [comment]
@NetanelBasal I've updated the commit message.

**Comment by vecernik** [comment]
Any eta for this fix?

**Comment by strigefleur** [comment]
@NetanelBasal sorry for reminder but could you please publish the new version now?

**Pull request merged**
