### PR TITLE
Angular 17

### PR DESCRIPTION
**Pull request by lneumeier**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #631

## What is the new behavior?

- support angular 17

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Please update the commit message using npm run commit and mark it as a breaking change.

**Comment by lneumeier** [comment]
@NetanelBasal 

Should I update the spectator version as well because of a breaking change or is this something you do?

**Comment by NetanelBasal** [comment]
No, only the commit message

**Comment by lneumeier** [comment]
I updated the commit messages.

**Pull request merged**
