### PR TITLE
chore: upgrading to angular v9

### PR DESCRIPTION
**Pull request by codeNoobie**
- Upgraded angular dependencies to v9
- Removed deprecated initUIEvent with UIEvent constructor
- With latest typescript, spyOnProperty getter test failed for es2015
  due to js compilation. Changed test target to es5 to fix this.
- Upgraded karma and jasmine to latest

BREAKING CHANGE: This PR sets the angular peer dependencies to v9

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently, spectator is on Angular 8. It needs to be updated to v9, so that it can stay up to date with angular.
Issue Number: #262

## What is the new behavior?
Upgraded to Angular 9 and Typescript 3.7. Also made upgrades to test libraries.

## Does this PR introduce a breaking change?
```
[X] Yes
[ ] No
```

Since we are upgrading peer dependencies on Angular from v8 to v9, I am marking this as a breaking change. The consumers will have to upgrade to Angular v9 if they want to use this version of spectator.

### CODE REVIEW

**Comment by jogelin** [comment]
I don't see any modifications related to  `entryComponents`, shouldn't we remove it ?

I had to rollback entryComponents on my tests using spectator but I could remove them in my code when migrating to angular 9

**Comment by LayZeeDK** [comment]
This PR introduces breaking changes in terms of Angular and related dependencies so it requires a major release.

**Comment by NetanelBasal** [comment]
Sure, it will be v5.

**Comment by LayZeeDK** [comment]
@codeNoobie the type would then be `feat`, not `chore`.

**Comment by NetanelBasal** [comment]
@jogelin, for now, I prefer leaving `entryComponents`. You can remove it if you are working with Ivy.

**Comment by codeNoobie** [comment]
> It makes more sense to create a type such as:
> 
> `export type Token<T> = Type<T> | InjectionToken<T> | AbstractType<T>`
> 
> and use it in all places :)

The current Token<T> declaration uses locally declared `InjectableType<T>`. I am removing this as it will get covered by Type<T> and AbstractType<T> now.


```
/**
 * Type for classes that can be used as tokens for injection. We might be inclined to use Angular's `Type<T>` interface for this, however,
 * that interface cannot be used for abstract classes, which are also valid tokens. The `InjectableType<T>` supports both abstract and
 * concrete classes and thus is a more accurate definition of a class type which can be used for injection.
 */
export type InjectableType<T> = Function & { prototype: T };

/** Type representing valid typesafe token types for provider binding. */
export type Token<T> = InjectableType<T> | InjectionToken<T>;
```

**Comment by NetanelBasal** [comment]
Thanks, I will test it locally asap, and if everything is ok I will merge it with #266

**Pull request merged**
